"use client";

import { ArrowClockwise, Sparkle } from "@phosphor-icons/react";
import { useState, useTransition } from "react";
import { generateDayInsights, type DayInsights } from "@/app/(app)/dashboard/insights";
import { Reveal } from "@/components/motion/reveal";

const KIND_CHIP: Record<DayInsights["insights"][number]["kind"], string> = {
  win: "bg-flame/10 text-flame ring-flame/25",
  watch: "bg-danger/10 text-danger ring-danger/25",
  tip: "bg-carbs/10 text-carbs ring-carbs/25",
};

/**
 * AI coach card: on-demand Gemini analysis of one diary day. Results are
 * persisted server-side (ai_insights) and hydrate via `initial`, so an
 * analysis survives navigation. Mount with key={date} so state resets
 * when the user changes day.
 */
export function AiInsights({
  date,
  hasEntries,
  initial = null,
  generatedAt = null,
}: {
  date: string;
  hasEntries: boolean;
  initial?: DayInsights | null;
  generatedAt?: string | null;
}) {
  const [result, setResult] = useState<DayInsights | null>(initial);
  const [isFresh, setIsFresh] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [isPending, startTransition] = useTransition();

  const run = () => {
    setError(null);
    startTransition(async () => {
      const res = await generateDayInsights(date);
      if (res.error) setError(res.error);
      else {
        setResult(res.data);
        setIsFresh(true);
      }
    });
  };

  return (
    <Reveal as="section" onScroll={false} delay={0.15} className="rounded-2xl border border-ink-800 bg-ink-900/60">
      <header className="flex items-center justify-between gap-3 border-b border-ink-800 px-5 py-4">
        <div className="flex items-center gap-3">
          <span className="grid size-9 shrink-0 place-items-center rounded-lg bg-flame/10 ring-1 ring-inset ring-flame/25">
            <Sparkle weight="fill" className="size-4.5 text-flame" />
          </span>
          <div>
            <h2 className="font-display text-base font-semibold text-paper">AI coach</h2>
            <p className="text-[11px] text-paper-mute">
              A dietitian-style read of everything you logged
            </p>
          </div>
        </div>
        {result && (
          <button
            type="button"
            onClick={run}
            disabled={isPending}
            aria-label="Regenerate insights"
            className="btn-press rounded-md p-2.5 text-paper-mute hover:bg-ink-800 hover:text-paper disabled:opacity-40"
          >
            <ArrowClockwise className={`size-4 ${isPending ? "animate-spin" : ""}`} />
          </button>
        )}
      </header>

      <div className="px-5 py-4">
        {isPending ? (
          <div className="space-y-2.5 py-1" aria-live="polite" aria-busy="true">
            <p className="text-xs text-paper-mute">Reading your day…</p>
            {[82, 100, 64].map((w, i) => (
              <div
                key={i}
                className="h-3 animate-pulse rounded bg-ink-700"
                style={{ width: `${w}%`, animationDelay: `${i * 150}ms` }}
              />
            ))}
          </div>
        ) : result ? (
          <div className="space-y-4">
            <p className="font-display text-lg font-semibold tracking-tight text-paper">
              {result.summary}
            </p>
            <ul className="space-y-3">
              {result.insights.map((insight, i) => (
                <li key={i} className="flex items-start gap-3">
                  <span
                    className={`mt-0.5 shrink-0 rounded-full px-2 py-0.5 text-[10px] font-semibold uppercase tracking-[0.12em] ring-1 ring-inset ${KIND_CHIP[insight.kind]}`}
                  >
                    {insight.tag}
                  </span>
                  <p className="text-sm leading-relaxed text-paper-dim">{insight.text}</p>
                </li>
              ))}
            </ul>
            <p className="border-t border-ink-800 pt-3 text-[11px] text-paper-mute">
              {!isFresh && generatedAt
                ? `Saved ${new Date(generatedAt).toLocaleDateString("en-GB", {
                    day: "numeric",
                    month: "short",
                  })} — regenerate if the day changed. `
                : ""}
              Generated by Gemini — general guidance, not medical advice.
            </p>
          </div>
        ) : (
          <div className="flex flex-wrap items-center justify-between gap-4">
            <p
              role={error ? "alert" : undefined}
              className={`max-w-md text-sm ${error ? "text-danger" : "text-paper-dim"}`}
            >
              {error ??
                (hasEntries
                  ? "Get wins, warnings and food-level tips based on this day's meals and your targets."
                  : "Log a meal first — the coach needs something on the plate to work with.")}
            </p>
            {hasEntries && (
              <button
                type="button"
                onClick={run}
                className="btn-press rounded-xl bg-flame px-5 py-2.5 font-display text-sm font-bold uppercase tracking-wide text-flame-ink hover:bg-flame-deep"
              >
                {error ? "Try again" : "Analyse this day"}
              </button>
            )}
          </div>
        )}
      </div>
    </Reveal>
  );
}
