import { LegalPage } from "@/components/legal-page";
import { CONTACT_EMAIL, LEGAL_OPERATOR, SITE_NAME } from "@/lib/site";

export const metadata = { title: "Terms of service" };

export default function TermsPage() {
  return (
    <LegalPage title="Terms of service">
      <p>
        These terms govern your use of {SITE_NAME}, operated by {LEGAL_OPERATOR}. By creating an account you agree to
        them. Contact: <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
      </p>

      <h2>Not medical advice</h2>
      <p>
        {SITE_NAME} gives general nutrition and fitness information based on the data you log. It is not a doctor,
        dietitian or medical device, and nothing in the app — including the AI coach — is medical advice, diagnosis or
        treatment. Talk to a qualified professional before changing your diet if you are pregnant, have a medical
        condition, take medication, or have a history of disordered eating. If you feel unwell, stop and seek help.
      </p>

      <h2>AI features</h2>
      <p>
        Meal estimates, coach replies, insights and plans are generated by AI and can be wrong. Check numbers against
        your diary and food labels. AI features have daily and monthly usage limits, which may differ between the free
        and premium plans.
      </p>

      <h2>Your account</h2>
      <ul>
        <li>You must be at least 14, with a parent or guardian&rsquo;s agreement if you are a minor; the AI coach requires 18+.</li>
        <li>Keep your login secure. You are responsible for activity on your account.</li>
        <li>Don&rsquo;t misuse the service: no automated scraping, attempts to bypass limits, or abuse of the AI.</li>
      </ul>

      <h2>Your content</h2>
      <p>
        You own what you log. You give us permission to store and process it only to run the service for you, as
        described in the <a href="/privacy">privacy policy</a>.
      </p>

      <h2>Premium</h2>
      <p>
        Some features may require a paid plan. Prices, billing period and renewal terms are shown before you pay.
        Refunds are covered by the <a href="/refunds">refund policy</a>.
      </p>

      <h2>Availability and changes</h2>
      <p>
        We work to keep {SITE_NAME} available but can&rsquo;t guarantee it will be uninterrupted or error-free. We may
        change or discontinue features and will give reasonable notice of material changes to these terms.
      </p>

      <h2>Liability</h2>
      <p>
        To the extent the law allows, {SITE_NAME} is provided &ldquo;as is&rdquo; and we are not liable for indirect
        losses or for decisions you make based on the app. Nothing here limits rights you have under consumer law.
      </p>

      <h2>Ending your account</h2>
      <p>You can delete your account at any time from the Me page. We may suspend accounts that break these terms.</p>
    </LegalPage>
  );
}
